### ISSUE TITLE
NLPer

### ISSUE THREAD

**Issue by NLP-1217** [cnunlp/Chinese-Argumentative-Student-Essays-Dataset#1]
Hi，
Sorry to disturb you, is there an original code that will be attached to the paper(IJCAI-2021)?
I want to reference your approach as a baseline in my work.
I will appreciate that!

Siyuan
2021.10.9

**Comment by cnunlp** [comment]
Thank you for your attention.
The code has uploaded in the project.

**Comment by NLP-1217** [comment]
I‘ve noticed that～
Thanks！
